{
 "title": "Proxmox - Ceph Prometheus KHACH HANG DECO - DMS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Site", "label": "Site", "query": "prometheus" },
   { "name": "job", "label": "Job / Cluster", "query": { "query": "label_values(up, job)" } }
  ]
 },
 "panels": [
  { "title": "Cluster State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Health Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_health_status{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Detailed Alarms",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "max by (name, severity, message, job) (ceph_health_detail{job=~\"$job\"} > 0)"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_bytes{job=~\"$job\"}) by (job)",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_bytes{job=~\"$job\"}) by (job)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "PG Inconsistent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pg_inconsistent{job=~\"$job\"}) or vector(0)",
     "legendFormat": "Lỗi PG"
    }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{job=~\"$job\"})",
     "legendFormat": "Apply Latency"
    }
   ]
  },
  { "title": "OSD State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=~\"$job\"}) - count(ceph_osd_in{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=~\"$job\"} == 0) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (job) (ceph_osd_up{job=~\"$job\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (job) (ceph_osd_in{job=~\"$job\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSD Low",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(1, (ceph_osd_stat_bytes_used{job=~\"$job\"} / ceph_osd_stat_bytes{job=~\"$job\"}) * 100)",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD High",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, (ceph_osd_stat_bytes_used{job=~\"$job\"} / ceph_osd_stat_bytes{job=~\"$job\"}) * 100)",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD Used Class Nvme",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(1, (max by (ceph_daemon, job) (ceph_osd_stat_bytes_used{job=~\"$job\"}) /  max by (ceph_daemon, job) (ceph_osd_stat_bytes{job=~\"$job\"})  * 100)* on(ceph_daemon) group_left  max by (ceph_daemon) (ceph_osd_metadata{device_class=\"nvme\", job=~\"$job\"}))"
    },
    {
     "expr": "bottomk(1, \r\n  (\r\n    max by (ceph_daemon, job) (ceph_osd_stat_bytes_used{job=~\"$job\"}) \r\n    / \r\n    max by (ceph_daemon, job) (ceph_osd_stat_bytes{job=~\"$job\"}) \r\n    * 100\r\n  )\r\n  * on(ceph_daemon) group_left \r\n  max by (ceph_daemon) (ceph_osd_metadata{device_class=\"nvme\", job=~\"$job\"})\r\n)"
    }
   ]
  },
  {
   "title": "OSD Used Class SSD",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(1, \r\n  (\r\n    max by (ceph_daemon, job) (ceph_osd_stat_bytes_used{job=~\"$job\"}) \r\n    / \r\n    max by (ceph_daemon, job) (ceph_osd_stat_bytes{job=~\"$job\"}) \r\n    * 100\r\n  )\r\n  * on(ceph_daemon) group_left \r\n  max by (ceph_daemon) (ceph_osd_metadata{device_class=\"ssd\", job=~\"$job\"})\r\n)"
    },
    {
     "expr": "bottomk(1, \r\n  (\r\n    max by (ceph_daemon, job) (ceph_osd_stat_bytes_used{job=~\"$job\"}) \r\n    / \r\n    max by (ceph_daemon, job) (ceph_osd_stat_bytes{job=~\"$job\"}) \r\n    * 100\r\n  )\r\n  * on(ceph_daemon) group_left \r\n  max by (ceph_daemon) (ceph_osd_metadata{device_class=\"ssd\", job=~\"$job\"})\r\n)"
    }
   ]
  },
  {
   "title": "OSD Used Class HDD",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(1, \r\n  (\r\n    max by (ceph_daemon, job) (ceph_osd_stat_bytes_used{job=~\"$job\"}) \r\n    / \r\n    max by (ceph_daemon, job) (ceph_osd_stat_bytes{job=~\"$job\"}) \r\n    * 100\r\n  )\r\n  * on(ceph_daemon) group_left \r\n  max by (ceph_daemon) (ceph_osd_metadata{device_class=\"hdd\", job=~\"$job\"})\r\n)"
    },
    {
     "expr": "bottomk(1, \r\n  (\r\n    max by (ceph_daemon, job) (ceph_osd_stat_bytes_used{job=~\"$job\"}) \r\n    / \r\n    max by (ceph_daemon, job) (ceph_osd_stat_bytes{job=~\"$job\"}) \r\n    * 100\r\n  )\r\n  * on(ceph_daemon) group_left \r\n  max by (ceph_daemon) (ceph_osd_metadata{device_class=\"hdd\", job=~\"$job\"})\r\n)"
    }
   ]
  },
  {
   "title": "OSD Used Class HDD12T",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(1, (max by (ceph_daemon) (ceph_osd_stat_bytes_used{job=~\"$job\"}) / max by (ceph_daemon) (ceph_osd_stat_bytes{job=~\"$job\"}) * 100) * on(ceph_daemon) group_left max by (ceph_daemon) (ceph_osd_metadata{device_class=\"hdd12t\", job=~\"$job\"}))"
    },
    {
     "expr": "bottomk(1, (max by (ceph_daemon) (ceph_osd_stat_bytes_used{job=~\"$job\"}) / max by (ceph_daemon) (ceph_osd_stat_bytes{job=~\"$job\"}) * 100) * on(ceph_daemon) group_left max by (ceph_daemon) (ceph_osd_metadata{device_class=\"hdd\", job=~\"$job\"}))"
    }
   ]
  },
  { "title": "Proxmox Resource - HA Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Resource Cluster with HA Groups",
   "type": "table",
   "description": "Hiển thị thông tin tài nguyên cluster kèm theo HA Groups",
   "gridPos": { "h": 34, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "label_replace(pve_cpu_usage_ratio{job=~\"$job\", id=~\"node/.*\"} * 100, \"host\", \"$1\", \"id\", \"node/(.*)\")"
    },
    {
     "expr": "label_replace((pve_memory_usage_bytes{job=~\"$job\", id=~\"node/.*\"} / pve_memory_size_bytes{job=~\"$job\", id=~\"node/.*\"}) * 100, \"host\", \"$1\", \"id\", \"node/(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(pve_memory_size_bytes{job=~\"$job\", id=~\"node/.*\"}, \"host\", \"$1\", \"id\", \"node/(.*)\")"
    },
    {
     "expr": "label_replace(pve_uptime_seconds{job=~\"$job\", id=~\"node/.*\"}, \"host\", \"$1\", \"id\", \"node/(.*)\")"
    },
    {
     "expr": "label_replace(pve_ha_state{job=~\"$job\", state=\"online\", id=~\"node/.*\"}, \"host\", \"$1\", \"id\", \"node/(.*)\")"
    },
    {
     "expr": "pve_ha_groups_custom_info{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "OSD CLASS DETAILS (HDD/SSD/NVME)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_cluster_by_class_total_bytes{job=~\"$job\"})"
    },
    {
     "expr": "sum by (device_class) (ceph_cluster_by_class_total_bytes{job=~\"$job\"}) \r\n- \r\nsum by (device_class) (ceph_cluster_by_class_total_used_bytes{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_cluster_by_class_total_used_bytes{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_cluster_by_class_total_used_bytes{job=~\"$job\"})"
    },
    {
     "expr": "(\r\n  sum by (device_class, job) (ceph_cluster_by_class_total_used_bytes{job=~\"$job\"}) \r\n  / \r\n  sum by (device_class, job) (ceph_cluster_by_class_total_bytes{job=~\"$job\"})\r\n) * 100"
    }
   ]
  },
  {
   "title": "CEPH POOL DETAILS ",
   "type": "table",
   "gridPos": { "h": 33, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "(ceph_pool_metadata{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_pg_total{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_pool_stored{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_pool_stored{job=~\"$job\"})"
    },
    { "expr": "0" },
    {
     "expr": "(ceph_pool_objects{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_pool_bytes_used{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_pool_bytes_used{job=~\"$job\"})"
    },
    { "expr": "0" },
    {
     "expr": "(ceph_pool_percent_used{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_pool_max_avail{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_pool_quota_objects{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_pool_quota_bytes{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_pool_dirty{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_pool_compress_bytes_used{job=~\"$job\"})"
    },
    {
     "expr": "(ceph_pool_compress_under_bytes{job=~\"$job\"})"
    }
   ]
  },
  { "title": "Latency Top 5 High", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "OSD Apply Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{job=~\"$job\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Top 5 NVME High Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, \r\n  avg by (ceph_daemon, hostname) (\r\n    ceph_osd_apply_latency_ms{job=~\"$job\"} \r\n    * on(ceph_daemon) group_left(hostname) \r\n    (max by (ceph_daemon, hostname) (ceph_osd_metadata{device_class=\"nvme\", job=~\"$job\"}))\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Top 5 SSD High Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, \r\n  ceph_osd_apply_latency_ms{job=~\"$job\"} \r\n  * on(ceph_daemon) group_left(hostname) \r\n  (max by (ceph_daemon, hostname) (ceph_osd_metadata{device_class=\"ssd\", job=~\"$job\"}))\r\n)"
    }
   ]
  },
  {
   "title": "TOP 5 HDD High Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, avg by (ceph_daemon, hostname) (ceph_osd_apply_latency_ms{job=~\"$job\"} * on(ceph_daemon) group_left(hostname) (avg by (ceph_daemon, hostname) (ceph_osd_metadata{device_class=\"hdd\", job=~\"$job\"}))))"
    }
   ]
  },
  {
   "title": "Top 5 HDD12T High Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, avg by (ceph_daemon, hostname) (ceph_osd_apply_latency_ms{job=~\"$job\"} * on(ceph_daemon) group_left(hostname) (avg by (ceph_daemon, hostname) (ceph_osd_metadata{device_class=\"hdd12t\", job=~\"$job\"}))))"
    }
   ]
  },
  {
   "title": "Ceph Recovery & Rebalance Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 }
  },
  {
   "title": "Ceph Status",
   "type": "stat",
   "description": "Hiển thị dòng trạng thái giống giao diện Proxmox (Chỉ hiện trạng thái mới nhất)",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 129 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_custom_recovery_info{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Health (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_custom_recovery_percent{job=~\"$job\"}",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Recovery Speed (Tốc độ phục hồi)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "ceph_custom_recovery_speed_bytes{job=~\"$job\"}",
     "legendFormat": "Recovery Speed"
    }
   ]
  }
 ]
}